[theme]
base = "light"
primaryColor = "#4caf50"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#2e7d32"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
